version: "3.4"

networks:
  nginx-net:
    driver: bridge
  back-bd:
    driver: bridge

services:
  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - back-api 
    networks:
      - nginx-net
  back-api:
    build:
      context: . 
      dockerfile: english-trainer-back/Dockerfile
    container_name: backend
    expose:
      - 5000
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__Default=User ID=postgres; Server=db;Port=5432; IntegratedSecurity=true; Pooling=true; Database=english_trainer_db;
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - nginx-net
      - back-bd
    restart: unless-stopped
    depends_on:
      - db
  db: 
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=english_trainer_bd
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=pass
    ports:
      - "49153:5432"
    restart: always
    networks:
      - back-bd
    volumes:
      - app_data:/var/lib/postgresql/data       
volumes:
  app_data:  
         